# pytorch_lightning==1.7.6
seed_everything: true
trainer:

    # comment this line out if you're training without a gpu
    accelerator: 'gpu'
    
    # number of epochs to run for. `-1` means run forever (until you interrupt manually)
    max_epochs: -1
    
    devices: 1
    precision: 16-mixed

    enable_checkpointing: true
    callbacks:
        - # keep the best performing checkpoint
            class_path: pytorch_lightning.callbacks.ModelCheckpoint
            init_args:
                monitor: val/l2_rec
                mode: min
                save_top_k: 1
        - # learning rate monitor
            class_path: pytorch_lightning.callbacks.LearningRateMonitor


    logger:
        class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
            save_dir: runs
            name: latent

    enable_progress_bar: true
    log_every_n_steps: 1
    enable_model_summary: true

    val_check_interval: 1000
    check_val_every_n_epoch: null
    
data:
    # length of each training subsequence
    seq_len: 2048 # * 6ms/frame ~= 24.6s
    
    # size of training batch
    batch_size: 20
    
    # number of workers to use for data loading
    num_workers: 6
    
    # number of samples to hold out for validation
    # must be at least one in order to render validation plots
    val_size: 128
    # val_split: .1
    
model:
    # training parameters
    opt_args:
        lr: .002
        weight_decay: 0.
    grad_accum_steps: 1
    gp_factor: 10.
    gan_factor: 5e-3
    fm_factor: 1.
    pixel_factor: 0.
    kl_factor: .001

    # model hyperparameters
    emb_dim: 24
    h_dim: 320
    ae_args:
        strides: [3, 3]
        layer_args:
            num_stacks: 1
            stack_depth: 4

    critic_args:
        scales: 3
        convs:
            - [  16, 3, 1,  1]
            - [  64, 5, 2,  4]
            - [ 256, 5, 2, 16]
            - [ 512, 5, 2, 64]
            - [ 512, 3, 1,  1]