seed_everything: true

trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed

  enable_checkpointing: true
  callbacks:
      - # keep the best performing checkpoint
          class_path: pytorch_lightning.callbacks.ModelCheckpoint
          init_args:
              monitor: val/loss
              mode: min
              save_top_k: 1
      - # early stopping
          class_path: pytorch_lightning.callbacks.EarlyStopping
          init_args:
              monitor: val/loss
              mode: min
              patience: 5
      - # learning rate monitor
          class_path: pytorch_lightning.callbacks.LearningRateMonitor

  logger:
      class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
          save_dir: runs
          name: lm

  max_epochs: -1
  enable_progress_bar: true
  enable_model_summary: true
  log_every_n_steps: 1
  val_check_interval: 1000
  check_val_every_n_epoch: null

data:
  context_size: 128
  batch_size: 12
  num_workers: 8
  val_size: 128
  data_path: ./data

model:

  opt_args:
    lr: 1e-4
  schedule_args:
    warmup_steps: 1000
    warmup_init: 0.1
    decay_start: 10000
    
  emb_dim: 128
  ctx_dim: 64

  audio_h_dim: 128
  num_global_ctx: 8

  decoder_args:
    n_heads: 8
    n_layers: 8
    dropout: 0.1