seed_everything: true

trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 16-mixed

  enable_checkpointing: true
  callbacks:
      - # keep the best performing checkpoint
          class_path: pytorch_lightning.callbacks.ModelCheckpoint
          init_args:
              monitor: val/loss
              mode: min
              save_top_k: 1
      - # early stopping
          class_path: pytorch_lightning.callbacks.EarlyStopping
          init_args:
              monitor: val/loss
              mode: min
              patience: 5
      - # learning rate monitor
          class_path: pytorch_lightning.callbacks.LearningRateMonitor

  logger:
      class_path: pytorch_lightning.loggers.TensorBoardLogger
      init_args:
          save_dir: runs
          name: lm

  max_epochs: -1
  enable_progress_bar: true
  enable_model_summary: true
  log_every_n_steps: 1
  val_check_interval: 1000
  check_val_every_n_epoch: null

data:
  context_size: 512
  batch_size: 24
  num_workers: 8
  val_size: 128
  data_path: ./data

  vocab:
    time_bins: 6144 # * 6ms = 36.9s

model:

  # training params
  opt_args:
    lr: .003
    weight_decay: 0.01
  timing_jitter: 3 # * 6ms = 18ms

  # sampling params
  context_shift_threshold: 0.8
  context_shift_amount: 0.5

  schedule_args:
    warmup_steps: 2000
    warmup_init: 0.05
    decay_start: 15000
    
  emb_dim: 512
  ctx_dim: 384

  decoder_args:
    n_heads: 16
    n_layers: 12
    dropout: 0.15