# pytorch_lightning==1.7.6
seed_everything: true
trainer:

    # comment this line out if you're training without a gpu
    accelerator: 'gpu'
    
    # number of epochs to run for. `-1` means run forever (until you interrupt manually)
    max_epochs: -1
    
    devices: 1
    precision: bf16-mixed

    enable_checkpointing: true
    callbacks:
        - # keep the best performing checkpoint
            class_path: pytorch_lightning.callbacks.ModelCheckpoint
            init_args:
                monitor: eval/score
                mode: max
                save_top_k: 1
        - # learning rate monitor
            class_path: pytorch_lightning.callbacks.LearningRateMonitor
        - # stop once the eval score stops improving
            class_path: pytorch_lightning.callbacks.EarlyStopping
            init_args:
                monitor: eval/score
                mode: max
                patience: 10
                min_delta: 0.001


    logger:
        class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
            save_dir: runs
            name: latent

    enable_progress_bar: true
    log_every_n_steps: 4
    enable_model_summary: true

    # val_check_interval: { "minutes": 10 }
    # check_val_every_n_epoch: null

    gradient_clip_val: 1.
    
data:
    # length of each training subsequence
    seq_len: 1024 # * 6ms/frame ~= 6.1s
    
    # size of training batch
    batch_size: 64
    
    # number of workers to use for data loading
    num_workers: 13
    
    # number of samples to hold out for validation
    # must be at least one in order to render validation plots
    val_size: 64

    # number of samples to take per map
    # values < 1 take as many non-overlapping samples as possible
    max_per_map: 5
    
model:
    # training parameters
    opt_args:
        lr: .001
        weight_decay: 0.01
    schedule_args:
        warmup_init: .1
        warmup_steps: 2000
    z_reg_weight: .001
    s_reg_weight: 1.
    s_noise: .2

    # model hyperparameters
    emb_dim: 8
    style_dim: 16
    n_downs: 3
    stride: 3
    latent_args:
        h_dim: 128
        ae_args:
            n_layers: 3
            expand: 3
            radius: 1
        label_args:
            h_dim: 256
            grad_factor: .1