# pytorch_lightning==1.7.6
seed_everything: true
trainer:

    # comment this line out if you're training without a gpu
    accelerator: 'gpu'
    
    # number of epochs to run for. `-1` means run forever (until you interrupt manually)
    max_epochs: -1
    
    devices: 1
    precision: 16-mixed

    enable_checkpointing: true
    callbacks:
        - # keep the best performing checkpoint
            class_path: pytorch_lightning.callbacks.ModelCheckpoint
            init_args:
                monitor: val/loss
                mode: min
                save_top_k: 1
        - # early stopping
            class_path: pytorch_lightning.callbacks.EarlyStopping
            init_args:
                monitor: val/loss
                mode: min
                patience: 10

    logger:
        class_path: pytorch_lightning.loggers.TensorBoardLogger
        init_args:
            save_dir: runs
            name: denoiser

    accumulate_grad_batches: 2
    enable_progress_bar: true
    log_every_n_steps: 1
    enable_model_summary: true
    
data:
    # length of each training subsequence
    seq_len: 1024 # ~8s @ 8ms/frame
    
    # affects how many samples are generated from a single beatmap (per epoch)
    # higher number means more samples from the same beatmap
    subseq_density: .1
    
    # size of training batch
    batch_size: 16
    
    # number of workers to use for data loading
    num_workers: 6
    
    # number of samples to hold out for validation
    # must be at least one in order to render validation plots
    val_size: 128
    # val_split: .1
    
model:
    # validation parameters
    val_steps: 32
    val_batches: 64

    # training parameters
    opt_args:
        lr: .0001

    # model hyperparameters
    diffusion_args:
        log_snr_scale: 3.
        log_snr_bound: 3e-2
        std_data: .73

    denoiser_args:
        h_dim: 256
        cbam_reduction: 8

        c_features: 256
        c_dim: 256

        wavenet_args:
            num_stacks: 6
            stack_depth: 6